---
version: '3'
services:
    postgres:
    image: postgres:13.3
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: jessie123
